"""add-favorite-number

Revision ID: 2b6dbb3b0a9b
Revises: 
Create Date: 2020-04-19 21:39:49.564770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6dbb3b0a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('favorite_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'favorite_number')
    # ### end Alembic commands ###
